#!/usr/bin/env node
/**
 * Generates skills-index.json from the SKILL.md frontmatter.
 *
 * The index exists so the CLI can fetch one file to know every skill and every
 * file inside it. raw.githubusercontent.com has no directory listing, so without
 * a committed manifest the CLI would have to hit the GitHub API — which is rate
 * limited for anonymous callers and would make `npx rulebase-skills list` fail
 * exactly when a lot of people try it.
 *
 * CI runs this with --check to fail when the committed index is stale.
 *
 * Usage:
 *   node scripts/build-index.mjs           # write skills-index.json
 *   node scripts/build-index.mjs --check   # verify the committed copy is current
 */

import { readFileSync, writeFileSync, readdirSync, existsSync, statSync } from 'node:fs';
import { join, dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SKILLS_DIR = join(REPO_ROOT, 'skills');
const INDEX_PATH = join(REPO_ROOT, 'skills-index.json');

const CHECK = process.argv.includes('--check');

/**
 * Same deliberately-small YAML subset the validator accepts: `key: value`
 * scalars plus one level of two-space nesting under `metadata`.
 */
function parseFrontmatter(raw) {
  if (!raw.startsWith('---\n')) return null;
  const end = raw.indexOf('\n---', 3);
  if (end === -1) return null;

  const data = {};
  let parent = null;
  for (const line of raw.slice(4, end).split('\n')) {
    if (line.trim() === '' || line.trim().startsWith('#')) continue;
    const indent = line.length - line.trimStart().length;
    const m = /^([A-Za-z0-9_-]+):\s*(.*)$/.exec(line.trim());
    if (!m) continue;
    const [, key, rawValue] = m;
    let value = rawValue.trim();
    if (/^["'].*["']$/.test(value) && value.length > 1) value = value.slice(1, -1);

    if (indent === 0) {
      if (value === '') {
        data[key] = {};
        parent = key;
      } else {
        data[key] = value;
        parent = null;
      }
    } else if (parent) {
      data[parent][key] = value;
    }
  }
  return data;
}

/** Every file inside a skill directory, repo-relative, sorted for stable diffs. */
function listFiles(dir) {
  const out = [];
  const walk = (current) => {
    for (const entry of readdirSync(current, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
      if (entry.name.startsWith('.')) continue;
      const full = join(current, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (entry.isFile()) out.push(relative(dir, full));
    }
  };
  walk(dir);
  return out.sort();
}

function findSkillDirs(dir, depth = 1) {
  if (!existsSync(dir)) return [];
  if (existsSync(join(dir, 'SKILL.md'))) return [dir];
  if (depth >= 3) return [];
  const found = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (!entry.isDirectory() || entry.name.startsWith('.')) continue;
    found.push(...findSkillDirs(join(dir, entry.name), depth + 1));
  }
  return found;
}

const skills = [];
for (const dir of findSkillDirs(SKILLS_DIR).sort()) {
  const skillMd = join(dir, 'SKILL.md');
  const fm = parseFrontmatter(readFileSync(skillMd, 'utf8'));
  if (!fm?.name) {
    console.error(`error: ${relative(REPO_ROOT, skillMd)} has no parseable frontmatter name`);
    process.exit(2);
  }
  const relDir = relative(REPO_ROOT, dir);
  const category = relDir.split('/')[1] ?? null;
  const files = listFiles(dir);

  skills.push({
    slug: fm.name,
    category,
    path: relDir,
    description: fm.description ?? '',
    archetype: fm.metadata?.archetype ?? null,
    version: fm.metadata?.version ?? null,
    // The CLI downloads exactly these, so the list must be complete.
    files,
    hasScripts: files.some((f) => f.startsWith('scripts/')),
    hasReferences: files.some((f) => f.startsWith('references/')),
  });
}

const byCategory = {};
for (const s of skills) byCategory[s.category ?? 'uncategorised'] = (byCategory[s.category ?? 'uncategorised'] ?? 0) + 1;

// No generatedAt timestamp on purpose: it would make every rebuild a diff and
// break the --check comparison for no benefit. Git already records when.
const index = {
  $comment: 'Generated by scripts/build-index.mjs. Do not edit by hand; run `npm run build:index`.',
  repo: 'rulebase-co/rulebase-skills',
  branch: 'main',
  count: skills.length,
  categories: byCategory,
  skills,
};

const serialised = `${JSON.stringify(index, null, 2)}\n`;

if (CHECK) {
  if (!existsSync(INDEX_PATH)) {
    console.error('error: skills-index.json is missing. Run `npm run build:index` and commit it.');
    process.exit(1);
  }
  const committed = readFileSync(INDEX_PATH, 'utf8');
  if (committed !== serialised) {
    console.error('error: skills-index.json is stale. Run `npm run build:index` and commit the result.');
    process.exit(1);
  }
  console.error(`skills-index.json is current (${skills.length} skills).`);
} else {
  writeFileSync(INDEX_PATH, serialised);
  console.error(`wrote skills-index.json — ${skills.length} skills`);
  for (const [cat, n] of Object.entries(byCategory).sort()) console.error(`  ${cat.padEnd(22)} ${n}`);
}
